apply plugin: 'com.android.kotlin.multiplatform.library'
apply plugin: 'org.jetbrains.kotlin.multiplatform'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'
apply plugin: 'com.vanniktech.maven.publish'
apply plugin: 'org.jetbrains.dokka'
apply plugin: 'org.jetbrains.kotlinx.binary-compatibility-validator'

kotlin {
  explicitApi()

  android {
    namespace 'app.cash.molecule'

    withDeviceTestBuilder {
      sourceSetTreeName = 'test'
    }.configure {
      instrumentationRunner = 'androidx.test.runner.AndroidJUnitRunner'
    }

    withHostTest {
      returnDefaultValues = true
    }

    packaging.resources {
      excludes += 'META-INF/AL2.0'
      excludes += 'META-INF/LGPL2.1'
    }
  }

  iosArm64()
  iosSimulatorArm64()
  iosX64()

  js {
    browser()
  }

  jvm()

  linuxArm64()
  linuxX64()

  macosArm64()
  macosX64()

  mingwX64()

  tvosArm64()
  tvosSimulatorArm64()
  tvosX64()

  wasmJs {
    browser()
  }

  watchosArm32()
  watchosArm64()
  watchosSimulatorArm64()

  applyDefaultHierarchyTemplate {
    it.group("common") {
      it.group("java") {
        it.withAndroidTarget()
        it.withJvm()
      }
      it.group("darwin") {
        it.group("displayLink") {
          it.group("quartzCore") {
            it.group("ios") {}
            it.group("tvos") {}
          }
          it.group("macos") {}
        }
        it.group("watchos") {}
      }
      it.group('nonJava') {
        it.group('native') {}
        it.withJs()
        it.withWasmJs()
      }
    }
  }

  sourceSets {
    configureEach {
      languageSettings.optIn("kotlinx.cinterop.BetaInteropApi")
      languageSettings.optIn("kotlinx.cinterop.ExperimentalForeignApi")
    }

    commonMain {
      dependencies {
        api libs.androidx.compose.runtime
        api libs.kotlinx.coroutines.core
      }
    }
    commonTest {
      dependencies {
        implementation libs.kotlin.test
        implementation libs.assertk
        implementation libs.kotlinx.coroutines.test
      }
    }

    androidMain {
      dependsOn(javaMain)
      dependencies {
        implementation libs.androidx.core
      }
    }

    androidDeviceTest {
      kotlin.srcDir('src/androidInstrumentedTest/kotlin')
      dependencies {
        implementation libs.androidx.test.runner
        implementation libs.junit
        implementation libs.assertk
        implementation libs.kotlinx.coroutines.test
      }
    }
  }
}

dependencies {
  // The kotlin.test library provides JVM variants for multiple testing frameworks. When used
  // as a test dependency this selection is transparent. But since we are using from an Android
  // configuration we have to select the desired variant via an explicit capability.
  add("androidDeviceTestImplementation", libs.kotlin.test) {
    capabilities {
      requireCapability(
        "org.jetbrains.kotlin:kotlin-test-framework-junit:${libs.versions.kotlin.get()}")
    }
  }
}

apiValidation {
  klib.enabled = true
}

spotless {
  kotlin {
    targetExclude(
      // Apache 2-licensed files from AOSP.
      "src/androidMain/kotlin/app/cash/molecule/AndroidUiDispatcher.kt",
      "src/androidMain/kotlin/app/cash/molecule/AndroidUiFrameClock.kt",
    )
  }
}
