name: build

on:
  pull_request: {}
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1.0.5

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      # Main library
      - run: ./gradlew -p molecule build assembleAndroidTest dokkaHtmlMultiModule

      # Sample
      - run: ./gradlew build

      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 24
          script: ./gradlew -p molecule connectedCheck

      - run: ./gradlew -p molecule publish
        if: ${{ github.ref == 'refs/heads/trunk' && github.repository == 'cashapp/molecule' }}
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}

      - name: Deploy docs to website
        if: ${{ github.ref == 'refs/heads/trunk' }}
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: site
          FOLDER: molecule/build/dokka/htmlMultiModule
          TARGET_FOLDER: docs/latest/
          CLEAN: true
